version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust

  - package-ecosystem: npm
    directory: /tests-ts
    schedule:
      interval: weekly
    labels:
      - dependencies
      - typescript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
